name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      LAMBDA_PATH: ${{ secrets.LAMBDA_PATH }}
      LAMBDA_HANDLER: ${{ secrets.LAMBDA_HANDLER }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      REPORT_CRON: ${{ secrets.REPORT_CRON }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Install CDK dependencies
        run: |
          cd cdk
          npm install

      - name: Install Lambda dependencies
        run: |
          cd lambda-function
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target package/
          cp lambda_handler.py package/

      - name: Deploy CDK stack to AWS
        run: |
          cd cdk
          npx cdk bootstrap
          npx cdk deploy --require-approval never
